server:
  port: ${SERVICE_PORT}
  shutdown: graceful
  error:
    include-message: always
    include-exception: true # TODO make it false

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    addresses: ${RABBITMQ_ADDRESS}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
   # host: 127.0.0.1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    kubernetes:
      discovery:
        # TODO change false
        all-namespaces: true
      loadbalancer:
        mode: service
        enabled: true
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        # TODO *
        include: prometheus

rabbitmq:
  queue:
    name: mail-process-queue
  exchange:
    name: mail-process-exchange
  routing:
    key: mail-process-routing-key

frontEnd:
  # TODO change for prod
  url: ${FE_ADDRESS}

env:
  prod: true

services-list:
  mail-send-service: "http://mail-send-service"
  mail-process-service: "http://mail-porcess-service"
  car-history-service: "http://car-history-service"
  auth-service-service: "http://auth-service"
