apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-process
  labels:
    app: mail-process
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mail-process
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: mail-process
    spec:
      containers:
        - name: converter
          image: nullchefo/mail-process-service
          envFrom:
            - configMapRef:
                name: mail-process-configmap
            - secretRef:
                name: mail-process-secret
